INSERT INTO WOOD_TYPES
SELECT 
    (
    SELECT 
        MAX(WOOD_TYPE_ID) 
    FROM WOOD_TYPES
    ) + ROWNUM,
    WT.NAME,
    WT.PRICE*(1+WOOD_INCREASE.UP_PRICE),
    0,
    WT.DENSITY
FROM 
    (
    SELECT 
        SWO.WOOD_TYPE_ID, 
        AVG(SWO.WOOD_PRICE/AWO.WOOD_PRICE-0.5) UP_PRICE 
    FROM
        (SELECT OD.ORDER_ID, OD.WOOD_TYPE_ID, SUM(OD.AMOUNT*WT.PRICE) WOOD_PRICE 
         FROM ORDER_DETAILS OD, WOOD_TYPES WT 
         WHERE WT.WOOD_TYPE_ID=OD.WOOD_TYPE_ID AND WT.IS_ARCHIVED='0'
         GROUP BY OD.ORDER_ID, OD.WOOD_TYPE_ID) SWO,
        (SELECT OD.ORDER_ID, SUM(OD.AMOUNT*WT.PRICE) WOOD_PRICE 
         FROM ORDER_DETAILS OD, WOOD_TYPES WT 
         WHERE WT.WOOD_TYPE_ID=OD.WOOD_TYPE_ID AND WT.IS_ARCHIVED='0'
         GROUP BY ORDER_ID) AWO
    WHERE SWO.ORDER_ID=AWO.ORDER_ID AND SWO.WOOD_PRICE/AWO.WOOD_PRICE>0.5
    GROUP BY SWO.WOOD_TYPE_ID
    ) WOOD_INCREASE,
    WOOD_TYPES WT
WHERE 
    WOOD_INCREASE.WOOD_TYPE_ID=WT.WOOD_TYPE_ID
    AND WT.WOOD_TYPE_ID IN 
        (SELECT SW.WOOD_TYPE_ID 
         FROM 
            STORED_WOOD SW, 
            (SELECT STORAGE_ID, AVG(AMOUNT) AVG_AMONUT FROM STORED_WOOD GROUP BY STORAGE_ID) AVG_ALL, 
            STORAGES S
        WHERE 
            SW.STORAGE_ID=AVG_ALL.STORAGE_ID 
            AND SW.STORAGE_ID=S.STORAGE_ID
            AND S.CAPACITY>9000
        GROUP BY SW.WOOD_TYPE_ID, SW.STORAGE_ID 
        HAVING SUM(SW.AMOUNT)<SUM(AVG_ALL.AVG_AMONUT))
    AND WT.WOOD_TYPE_ID IN 
        (
        SELECT WT.WOOD_TYPE_ID 
        FROM 
            WOOD_TYPES WT,
            ORDER_DETAILS OD,
            ORDERS O
        WHERE 
            WT.WOOD_TYPE_ID=OD.WOOD_TYPE_ID 
            AND O.ORDER_ID=OD.ORDER_ID
            AND O.REALISATION_DATE>add_months(SYSDATE,-120)
        GROUP BY WT.WOOD_TYPE_ID
        HAVING COUNT(O.ORDER_ID)>100
        );
UPDATE WOOD_TYPES 
SET IS_ARCHIVED = '1' 
WHERE WOOD_TYPE_ID IN 
    (
    SELECT 
        WT.WOOD_TYPE_ID
    FROM 
        (
        SELECT 
            SWO.WOOD_TYPE_ID
        FROM
            (SELECT OD.ORDER_ID, OD.WOOD_TYPE_ID, SUM(OD.AMOUNT*WT.PRICE) WOOD_PRICE 
             FROM ORDER_DETAILS OD, WOOD_TYPES WT 
             WHERE WT.WOOD_TYPE_ID=OD.WOOD_TYPE_ID AND WT.IS_ARCHIVED='0' 
             GROUP BY OD.ORDER_ID, OD.WOOD_TYPE_ID) SWO,
            (SELECT OD.ORDER_ID, SUM(OD.AMOUNT*WT.PRICE) WOOD_PRICE 
             FROM ORDER_DETAILS OD, WOOD_TYPES WT 
             WHERE WT.WOOD_TYPE_ID=OD.WOOD_TYPE_ID AND WT.IS_ARCHIVED='0'
             GROUP BY ORDER_ID) AWO
        WHERE SWO.ORDER_ID=AWO.ORDER_ID AND SWO.WOOD_PRICE/AWO.WOOD_PRICE>0.5
        GROUP BY SWO.WOOD_TYPE_ID
        ) WOOD_INCREASE,
        WOOD_TYPES WT
    WHERE 
        WOOD_INCREASE.WOOD_TYPE_ID=WT.WOOD_TYPE_ID
        AND WT.WOOD_TYPE_ID IN 
            (SELECT SW.WOOD_TYPE_ID 
             FROM 
                STORED_WOOD SW, 
                (SELECT STORAGE_ID, AVG(AMOUNT) AVG_AMONUT FROM STORED_WOOD GROUP BY STORAGE_ID) AVG_ALL, 
                STORAGES S,
                WOOD_TYPES WT
            WHERE 
                SW.STORAGE_ID=AVG_ALL.STORAGE_ID 
                AND SW.STORAGE_ID=S.STORAGE_ID
                AND SW.WOOD_TYPE_ID=WT.WOOD_TYPE_ID
                AND S.CAPACITY>9000
            GROUP BY SW.WOOD_TYPE_ID, SW.STORAGE_ID 
            HAVING SUM(SW.AMOUNT)<SUM(AVG_ALL.AVG_AMONUT))
        AND WT.WOOD_TYPE_ID IN 
            (
            SELECT WT.WOOD_TYPE_ID 
            FROM 
                WOOD_TYPES WT,
                ORDER_DETAILS OD,
                ORDERS O
            WHERE 
                WT.WOOD_TYPE_ID=OD.WOOD_TYPE_ID 
                AND O.ORDER_ID=OD.ORDER_ID
                AND O.REALISATION_DATE>add_months(SYSDATE,-120)
            GROUP BY WT.WOOD_TYPE_ID
            HAVING COUNT(O.ORDER_ID)>100
            )
    );